# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aQuote', models.CharField(max_length=255)),
                ('aQuoter', models.CharField(max_length=50)),
            ],
        ),
    ]
